id: I4DE6EBB4
legacy_id: P004561
ocr_import_info:
  bdrc_scan_id: W1KG6189
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T20:22:43'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:46:54.923012+00:00'
last_modified: 2022-09-01 01:47:02.587089
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG6189
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG6189
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྔ་འགྱུར་མདོ་སྔགས་རིག་པའི་དགའ་ཚལ་གླིང་གི་ལོ་རྒྱུས་མུ་ཏིག་ཕྲེང་བ།
  author: པདྨ་ཆོས་འཕེལ།
statistics:
  ocr_word_mean_confidence_index: 0.961158068832077
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG6226:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG6226
      total_pages: 188
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG6226.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.961158068832077
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
