id: P004561
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:41:47.216586
source_metadata:
  id: bdr:W1KG6189
  title: སྔ་འགྱུར་མདོ་སྔགས་རིག་པའི་དགའ་ཚལ་གླིང་གི་ལོ་རྒྱུས་མུ་ཏིག་ཕྲེང་བ།
  author: ''
  volumes:
    a4665eb9c26d4f80af71671cc3179687:
      image_group_id: I1KG6226
      title: ''
      volume_number: 1
      total_pages: 188
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
